// ============================================================
// NBA BWARI DIGITAL PORTAL — MOCK DATA
// TODO: Replace with Laravel API calls via api.ts
// ============================================================

export const mockMember = {
  id: "MBR-2024-0042",
  nbaNumber: "NBA/ABJ/2019/1847",
  supremeCourtNumber: "SCN/2019/4521",
  fullName: "Barr. Adaeze Okonkwo",
  firstName: "Adaeze",
  lastName: "Okonkwo",
  email: "adaeze.okonkwo@lawfirm.ng",
  phone: "+234 803 456 7890",
  yearCalledToBar: 2019,
  membershipStatus: "Active" as const,
  goodStandingStatus: true,
  attendancePercentage: 78,
  votingEligibility: true,
  financialCompliance: true,
  avatar: null,
  branch: "Bwari Area Council Branch",
  residentialAddress: "15 Gwarimpa Estate, Abuja",
  role: "member" as const,
  lastLogin: "2025-07-29T08:30:00Z",
  joinedAt: "2019-11-15T00:00:00Z",
};

export const mockNotifications = [
  {
    id: "notif-1",
    type: "meeting" as const,
    title: "General Meeting Tomorrow",
    message: "Monthly general meeting scheduled for tomorrow at 10:00 AM — Bwari Community Centre",
    createdAt: "2025-07-29T09:00:00Z",
    read: false,
  },
  {
    id: "notif-2",
    type: "election" as const,
    title: "Election Period Opens",
    message: "Voting for Branch Chairman 2025 opens in 3 days. Verify your eligibility.",
    createdAt: "2025-07-28T14:30:00Z",
    read: false,
  },
  {
    id: "notif-3",
    type: "finance" as const,
    title: "Annual Dues Reminder",
    message: "2025 annual dues of ₦50,000 are due on 31st August 2025.",
    createdAt: "2025-07-27T10:00:00Z",
    read: true,
  },
  {
    id: "notif-4",
    type: "document" as const,
    title: "Good Standing Letter Ready",
    message: "Your Letter of Good Standing for July 2025 is ready for download.",
    createdAt: "2025-07-26T16:00:00Z",
    read: true,
  },
  {
    id: "notif-5",
    type: "announcement" as const,
    title: "New Circular Published",
    message: "NBA National Secretariat Circular No. 15/2025 has been published.",
    createdAt: "2025-07-25T09:00:00Z",
    read: true,
  },
];

export const mockMeetings = [
  {
    id: "mtg-1",
    title: "Monthly General Meeting — July 2025",
    date: "2025-07-30T10:00:00Z",
    venue: "Bwari Community Centre, Area 1",
    status: "upcoming" as const,
    attendanceOpen: false,
    attendanceCount: 0,
    totalMembers: 312,
  },
  {
    id: "mtg-2",
    title: "Emergency Meeting — AGM Preparation",
    date: "2025-07-15T14:00:00Z",
    venue: "NBA Bwari Branch Secretariat",
    status: "completed" as const,
    attendanceOpen: false,
    attendanceCount: 187,
    totalMembers: 312,
    memberAttended: true,
  },
  {
    id: "mtg-3",
    title: "Monthly General Meeting — June 2025",
    date: "2025-06-25T10:00:00Z",
    venue: "Bwari Community Centre, Area 1",
    status: "completed" as const,
    attendanceOpen: false,
    attendanceCount: 201,
    totalMembers: 312,
    memberAttended: true,
  },
  {
    id: "mtg-4",
    title: "Monthly General Meeting — May 2025",
    date: "2025-05-28T10:00:00Z",
    venue: "Bwari Community Centre, Area 1",
    status: "completed" as const,
    attendanceOpen: false,
    attendanceCount: 178,
    totalMembers: 312,
    memberAttended: false,
  },
  {
    id: "mtg-5",
    title: "Continuing Legal Education Seminar",
    date: "2025-05-10T09:00:00Z",
    venue: "Bwari Area Council Secretariat Hall",
    status: "completed" as const,
    attendanceOpen: false,
    attendanceCount: 225,
    totalMembers: 312,
    memberAttended: true,
  },
];

export const mockAttendanceHistory = [
  { month: "Jan", attended: 1, total: 1 },
  { month: "Feb", attended: 1, total: 1 },
  { month: "Mar", attended: 1, total: 2 },
  { month: "Apr", attended: 1, total: 2 },
  { month: "May", attended: 1, total: 2 },
  { month: "Jun", attended: 2, total: 2 },
  { month: "Jul", attended: 1, total: 1 },
];

export const mockElections = [
  {
    id: "elec-1",
    title: "NBA Bwari Branch Executive Elections 2025",
    description: "Annual election for branch executive positions for the 2025/2026 term.",
    status: "upcoming" as const,
    startDate: "2025-08-15T08:00:00Z",
    endDate: "2025-08-15T18:00:00Z",
    positions: ["Branch Chairman", "Vice Chairman", "Secretary", "Financial Secretary", "Welfare Secretary"],
    memberEligible: true,
    hasVoted: false,
  },
  {
    id: "elec-2",
    title: "NBA National Officers Election 2024",
    description: "National election for NBA national executive positions.",
    status: "completed" as const,
    startDate: "2024-09-01T08:00:00Z",
    endDate: "2024-09-01T18:00:00Z",
    positions: ["NBA President", "General Secretary", "Treasurer"],
    memberEligible: true,
    hasVoted: true,
  },
];

export const mockCandidates = [
  {
    id: "cand-1",
    electionId: "elec-1",
    position: "Branch Chairman",
    name: "Barr. Chukwuemeka Nwosu",
    nbaNumber: "NBA/ABJ/2010/0234",
    yearCalled: 2010,
    photo: null,
    manifesto: "I pledge to modernize the branch administration, improve member welfare, and represent our interests at the national level with dignity and purpose.",
    votes: 0,
  },
  {
    id: "cand-2",
    electionId: "elec-1",
    position: "Branch Chairman",
    name: "Barr. Fatimah Aliyu-Bello",
    nbaNumber: "NBA/ABJ/2012/0891",
    yearCalled: 2012,
    photo: null,
    manifesto: "My vision is a digitally-forward, financially transparent branch that serves every member with excellence. 15 years of practice and passion for our profession drives me.",
    votes: 0,
  },
  {
    id: "cand-3",
    electionId: "elec-1",
    position: "Branch Chairman",
    name: "Barr. Olumide Adeyemi",
    nbaNumber: "NBA/ABJ/2008/0112",
    yearCalled: 2008,
    photo: null,
    manifesto: "Experienced legal practitioner with strong advocacy record. I will fight for better infrastructure, reduced dues, and stronger CLE programs.",
    votes: 0,
  },
];

export const mockFinancials = {
  totalDuesPaid: 150000,
  outstandingPayments: 0,
  lastPaymentDate: "2025-01-15",
  complianceStatus: "compliant" as const,
  payments: [
    { id: "pay-1", description: "2025 Annual Dues", amount: 50000, date: "2025-01-15", status: "paid" as const },
    { id: "pay-2", description: "2024 Annual Dues", amount: 50000, date: "2024-02-10", status: "paid" as const },
    { id: "pay-3", description: "2023 Annual Dues", amount: 50000, date: "2023-03-05", status: "paid" as const },
    { id: "pay-4", description: "CLE Seminar Fee", amount: 10000, date: "2025-05-10", status: "paid" as const },
  ],
  monthlyData: [
    { month: "Jan", income: 4250, expenditure: 1800 },
    { month: "Feb", income: 3800, expenditure: 2100 },
    { month: "Mar", income: 5200, expenditure: 1950 },
    { month: "Apr", income: 2900, expenditure: 1700 },
    { month: "May", income: 6100, expenditure: 2300 },
    { month: "Jun", income: 4300, expenditure: 1600 },
    { month: "Jul", income: 3500, expenditure: 1400 },
  ],
};

export const mockDocuments = [
  {
    id: "doc-1",
    title: "Letter of Good Standing — July 2025",
    type: "good_standing" as const,
    issuedDate: "2025-07-01",
    expiryDate: "2025-12-31",
    size: "245 KB",
    format: "PDF",
  },
  {
    id: "doc-2",
    title: "NBA Circular No. 15/2025",
    type: "circular" as const,
    issuedDate: "2025-07-20",
    size: "1.2 MB",
    format: "PDF",
  },
  {
    id: "doc-3",
    title: "Branch Financial Report Q2 2025",
    type: "financial_report" as const,
    issuedDate: "2025-07-01",
    size: "3.4 MB",
    format: "PDF",
  },
  {
    id: "doc-4",
    title: "Annual General Meeting Minutes 2024",
    type: "report" as const,
    issuedDate: "2024-12-10",
    size: "890 KB",
    format: "PDF",
  },
  {
    id: "doc-5",
    title: "Election Notice — 2025 Branch Elections",
    type: "election_notice" as const,
    issuedDate: "2025-07-25",
    size: "156 KB",
    format: "PDF",
  },
];

export const mockNewsItems = [
  {
    id: "news-1",
    title: "NBA Bwari Hosts Successful CLE Seminar on Digital Law",
    category: "branch_news" as const,
    excerpt: "Over 200 members attended the continuing legal education seminar on emerging digital law frameworks in Nigeria, featuring keynote speakers from top tech law firms.",
    date: "2025-07-20",
    readTime: "4 min read",
    featured: true,
  },
  {
    id: "news-2",
    title: "New Branch Secretariat Office Opens in Bwari",
    category: "announcement" as const,
    excerpt: "The Bwari Area Council Branch of the Nigerian Bar Association is proud to announce the opening of its new ultra-modern secretariat office at Area 3, Bwari.",
    date: "2025-07-15",
    readTime: "2 min read",
    featured: false,
  },
  {
    id: "news-3",
    title: "Call for Nominations: 2025 Branch Executive Elections",
    category: "election" as const,
    excerpt: "Nominations are now open for all positions in the upcoming 2025 NBA Bwari Branch Executive Elections. All eligible members are encouraged to participate.",
    date: "2025-07-10",
    readTime: "3 min read",
    featured: false,
  },
  {
    id: "news-4",
    title: "NBA National Body Launches New Legal Aid Initiative",
    category: "national_news" as const,
    excerpt: "The Nigerian Bar Association has announced a new legal aid initiative targeting underserved communities across Nigeria, with Bwari Branch participating as a pilot.",
    date: "2025-07-05",
    readTime: "5 min read",
    featured: false,
  },
];

export const mockAdminStats = {
  totalMembers: 312,
  activeMembers: 287,
  attendanceRate: 72,
  financialCompliance: 81,
  votingParticipation: 68,
  goodStandingCount: 256,
  pendingApprovals: 7,
  upcomingMeetings: 2,
};
